version: "3.3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8000"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg:5432/sharedlist
      - SPRING_DATASOURCE_USERNAME=shl
      - SPRING_DATASOURCE_PASSWORD=123
  postgres:
    image: "postgres"
    container_name: pg
    environment:
      POSTGRES_DB: "sharedlist"
      POSTGRES_USER: "shl"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
